version: '2'

services:
  web:
    restart: always
    build: ./
    expose:
    - "8000"
    links:
    - postgres:postgres
    volumes:
    - /usr/src/app/static
    command: python3 run.py runserver --host=0.0.0.0 --port=8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
    - "80:80"
    volumes:
    - /www/static
    volumes_from:
    - web
    links:
    - web:web

  data:
    restart: "no"
    image: postgres:latest
    volumes:
    - /var/lib/postgresql
    command: "true"

  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
    - data
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: lupusanay
      POSTGRES_PASSWORD: pass123